version: '3.8'

services:
  postgres:
    container_name: nodejs-typescript-prisma-api-pg
    image: postgres
    ports:
      - 5432:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    volumes:
      - ./data/pg:/data/postgres
